/**
 * Every string literal in Table's two ingredient-line test files at cb7b56e
 * (tests/unit/recipe-import-ingredient-line.test.ts, tests/unit/recipe-import-ingredient-suggest.test.ts), in source
 * order, de-duplicated, import specifiers excluded: inputs, expected values and test titles alike are used as
 * parity inputs. Non-ASCII characters are written as escapes so no bidi control appears raw in this file.
 */
export const TABLE_TEST_LITERALS: readonly string[] = [
  "parseIngredientLine parsed lines", "2 cups flour", "2", "cup", "flour", "1/2 cup sugar", "0.5", "sugar", "3/4 tsp salt", "0.75", "tsp",
  "salt", "\u00bd cup milk", "milk", "\u215b tsp cayenne", "0.125", "cayenne", "\u00be cup oats", "oats", "1\u00bd cups water", "1.5",
  "water", "1 \u00bd cups water", "1 1/2 cups rice", "rice", "2 1/4 cups flour", "2.25", "1\u20442 cup broth", "broth", "5/8 cup cream",
  "0.625", "cream", "0.5 cup oil", "oil", ".5 cup oil", "1.25 lb beef", "1.25", "lb", "beef", "1.50 lb beef", "2 T butter", "tbsp",
  "butter", "2 Tbsp butter", "2 TBSP butter", "1 tbsp. honey", "1", "honey", "2 tablespoons honey", "1 t salt", "1 tsp salt",
  "1 teaspoon salt", "1 c milk", "1 C milk", "2 Cups Flour", "Flour", "2 lbs chicken thighs", "chicken thighs", "1 pound ground turkey",
  "ground turkey", "8 oz cheddar", "8", "oz", "cheddar", "8 ounces cheddar", "8 fl oz milk", "fl_oz", "8 fl. oz. cream",
  "8 fluid ounces cream", "200g flour", "200", "g", "200 grams flour", "1.5kg potatoes", "kg", "potatoes", "500 ml stock", "500", "ml",
  "stock", "500 mL stock", "1 L water", "l", "1 litre water", "2 eggs", "each", "eggs", "3 large eggs", "3", "1 onion, diced", "onion",
  "4 each tortillas", "4", "tortillas", "2 cups of flour", "- 2 cups flour", "\u2022 1 cup rice", "  2   cups   flour  ", "10000 g sugar",
  "10000", "%j \u2192 %s %s %j", "parsed", "parseIngredientLine review lines", "salt to taste", "Salt and pepper, to taste",
  "fresh parsley, for serving", "water as needed", "1 tsp vanilla (optional)", "optional: 1 cup nuts", "one egg", "a pinch of salt",
  "2-3 cups broth", "2 to 3 cups broth", "2 \u2013 3 tbsp oil", "1/2-1 cup water", "1 or 2 eggs", "1 cup milk or cream", "3 cloves garlic",
  "1 clove garlic", "1 can black beans", "2 cans tomatoes", "1 bunch cilantro", "1 pinch salt", "1 dash hot sauce", "1 handful spinach",
  "1 package tofu", "1 jar salsa", "2 slices bread", "3 sprigs thyme", "1 head lettuce", "2 stalks celery", "4 pieces chicken",
  "1 stick butter", "1 bag spinach", "1 box pasta", "2 quarts water", "1 (15 oz) can black beans", "1 can (14.5 oz) diced tomatoes",
  "1 lb 4 oz beef", "1 cup 2% milk", "1 cup \u00bd and \u00bd", "1/3 cup sugar", "\u2153 cup sugar", "\u2154 cup milk", "1 1/3 cups flour",
  "1\u2153 cups flour", "1/6 tsp pepper", "\u215a cup broth", "2/12 cup broth", "1/0 cup water", "0/4 cup water", "1 3/2 cup water",
  "0 cups flour", "0.0 cups flour", "20000 g sugar", "123456789012 g sugar", "1,5 cups milk", "1,000 g flour", "1. Preheat the oven",
  "2eggs", "1 cup", "", "   ", "-1 cup water", "%j \u2192 review (%s)", "requires_review", "; ",
  "keeps the unit word in the name when the unit is unsupported", "3 cloves garlic, minced", "cloves garlic", "minced",
  "an unsupported unit alongside another reason drops the quantity too", "1 can tomatoes, or fresh",
  "parseIngredientLine form and robustness", "3 cups cooked rice", "cooked", "2 cups rice, cooked", "1 lb pre-cooked shrimp",
  "1 lb raw shrimp", "raw", "1 cup uncooked rice", "1 cup Uncooked rice", "1 cup rice", "2 cups strawberries", "1 cup precooked rice",
  "%j \u2192 form %s", "quantities are exact decimal strings, never floats", "0.1 cup water", "0.1", "1/1024 tsp salt", "0.0009765625",
  "0.000001 g saffron", "0.000001", "3/2 cups milk", "never throws on hostile input and stays fast", "1 ", "(", "\u00bd", "1/",
  "<script>alert(1)</script>", "\u0000\u202e1 cup", "price annotations", "1 Tbsp olive oil ($0.16)", "olive oil",
  "1 yellow onion, diced ($0.42)", "yellow onion", "diced", "1 tsp smoked paprika ($.10)", "smoked paprika",
  "2 cups long grain rice ($1.23*)", "long grain rice", "1/2 tsp salt ( $0.02 )", "($0.50) 2 eggs", "1 cup milk ($0.25) ($0.25)",
  "%j is parsed; the price is not a quantity", "1 cup milk ($0.25 each)", "1 cup milk (about $1)", "1 cup milk $0.25",
  "1 (15 oz) can beans ($0.89)", "%j: only a price-only parenthetical is removed", "name and note", "1 large onion, diced", "large; diced",
  "2 cups flour (packed)", "packed", "1 cup walnuts, chopped, toasted", "walnuts", "chopped, toasted", "2 medium carrots", "carrots",
  "medium", "3 small potatoes", "small", "3 extra large eggs", "extra large", "2 Extra-Large eggs (room temperature)",
  "extra-large; room temperature", "1 lb chicken thighs (boneless, skinless), cubed", "boneless, skinless; cubed",
  "1 large onion (yellow), diced", "large; yellow; diced", "2 large", "large", "1 cup largest berries", "largest berries", "2 cups broth,",
  "%j \u2192 name %j, note %j (parsed)", "review lines are split too, and raw is untouched", "Salt and pepper", "to taste",
  "1 tsp vanilla", "optional", "1 (15 oz) can black beans, drained", "drained",
  "splitNote keeps text when nothing would be left of the name", "(optional)", ", diced", "onion (1/2 cup)", "suggestions: use", "0.3333",
  "\u2153 rounded to 0.3333", "0.6667", "\u2154 rounded to 0.6667", "1/3 rounded to 0.3333", "1.3333", "1 1/3 rounded to 1.3333",
  "1\u2153 rounded to 1.3333", "0.1667", "pepper", "1/6 rounded to 0.1667", "0.8333", "\u215a rounded to 0.8333", "2/12 rounded to 0.1667",
  "1/7 cup oats", "0.1429", "1/7 rounded to 0.1429", "1/3 cup chopped parsley ($0.30)", "chopped parsley", "1 quart = 4 cups",
  "1 qt. stock", "1 pint cream", "1 pint = 2 cups", "1/2 gallon milk", "1 gallon = 16 cups", "1/3 quart broth",
  "rounded to 1.3333; 1 quart = 4 cups", "15", "black beans", "1 can \u00d7 15 oz", "1 (15 oz.) can black beans, drained ($0.89)",
  "2 (14.5-ounce) cans diced tomatoes", "29", "diced tomatoes", "2 cans \u00d7 14.5 oz", "2 (14.5 oz) cans diced tomatoes ($1.78*)",
  "1 can (15 oz) black beans", "14.5", "1 can \u00d7 14.5 oz", "2 cans (14.5 oz each) tomatoes", "tomatoes", "1 15-oz can chickpeas",
  "chickpeas", "2 28 ounce cans crushed tomatoes", "56", "crushed tomatoes", "2 cans \u00d7 28 oz", "1 12 fl oz bottle beer", "12", "beer",
  "1 bottle \u00d7 12 fl oz", "1 (12 fl. oz) bottle seltzer", "seltzer", "1 (400 g) tin chickpeas", "400", "1 tin \u00d7 400 g",
  "1 (1 lb) bag frozen peas", "frozen peas", "1 bag \u00d7 1 lb", "2 (500 ml) cartons stock", "1000", "2 cartons \u00d7 500 ml",
  "1 (1.5 L) bottle water", "1 bottle \u00d7 1.5 l", "3 (0.25 oz) packets yeast", "yeast", "3 packets \u00d7 0.25 oz",
  "1 pkg (8 oz) cream cheese, softened", "cream cheese", "1 package \u00d7 8 oz", "2 (6-ounce) salmon fillets", "salmon fillets",
  "2 \u00d7 6 oz", "\u00bd (15 oz) can beans", "7.5", "beans", "\u00bd can \u00d7 15 oz", "1/3 (15 oz) can beans", "5",
  "1/3 can \u00d7 15 oz", "1 (2/3 oz) packet gelatin", "gelatin", "rounded to 0.6667; 1 packet \u00d7 2/3 oz", "garlic (clove)",
  "counted as cloves", "2 cloves of garlic", "black beans (can)", "counted as cans", "tomatoes (can)", "cilantro (bunch)",
  "counted as bunches", "lettuce (head)", "counted as heads", "celery (stalk)", "counted as stalks", "thyme (sprig)", "counted as sprigs",
  "bread (slice)", "counted as slices", "chicken (piece)", "counted as pieces", "butter (stick)", "counted as sticks", "2 ears corn",
  "corn (ear)", "counted as ears", "3 leaves basil", "basil (leaf)", "counted as leaves", "1 loaf bread", "bread (loaf)",
  "counted as loaves", "tofu (package)", "counted as packages", "salsa (jar)", "counted as jars", "spinach (bag)", "counted as bags",
  "pasta (box)", "counted as boxes", "2 fillets cod", "cod (fillet)", "counted as fillets", "1 block tofu", "tofu (block)",
  "counted as blocks", "\u2153 bunch parsley", "parsley (bunch)", "\u2153 rounded to 0.3333; counted as bunches",
  "range: used the larger amount", "3-2 tbsp oil", "2-3 cloves garlic", "range: used the larger amount; counted as cloves",
  "1-2 quarts water", "range: used the larger amount; 1 quart = 4 cups", "\u2153-\u2154 cup sugar",
  "\u2154 rounded to 0.6667; range: used the larger amount", "alternatives: used the first (milk)", "2 tbsp butter or 1 tbsp oil",
  "alternatives: used the first (butter)", "1 cup whole milk or cream", "whole milk", "alternatives: used the first (whole milk)",
  "1 cup (240 ml) milk", "kept the first amount; dropped (240 ml)", "1 lb (450 g) chicken", "chicken",
  "kept the first amount; dropped (450 g)", "2 (about 1 lb) potatoes", "kept the first amount; dropped (about 1 lb)",
  "1 pint (2 cups) cream", "1 pint = 2 cups; kept the first amount; dropped (2 cups)", "vanilla", "used the stated amount",
  "1 tsp salt, or to taste", "1 tsp salt to taste", "1 cup broth, or water", "%j \u2192 %s %s %j (%s)", "carries the form",
  "\u2153 cup cooked rice", "cooked rice", "\u2153 cup uncooked rice", "\u2153 cup rice",
  "never touches the parsed fields of a review line", "suggestions: leave out", "no fixed amount: leave it out of grocery amounts",
  "lime wedges, for garnish", "flour, for dusting", "oil for frying", "chili flakes (optional)",
  "a pinch: no fixed amount; leave it out of grocery amounts", "Pinch of saffron", "2 pinches salt",
  "a dash: no fixed amount; leave it out of grocery amounts", "a few drops vanilla",
  "a drop: no fixed amount; leave it out of grocery amounts", "2-3 drops food coloring", "a splash of milk",
  "a splash: no fixed amount; leave it out of grocery amounts", "2 splashes milk",
  "a handful: no fixed amount; leave it out of grocery amounts", "a small handful of herbs", "a sprinkle of sesame seeds",
  "a sprinkle: no fixed amount; leave it out of grocery amounts", "2 sprinkles salt", "%j \u2192 leave out (%s)",
  "suggestions: none when unclear", "Juice of 1 lemon", "1 cup plus 2 tbsp flour", "1 cup flour, plus 2 tbsp",
  "1 onion, cut into 8 wedges", "1 cup chicken or vegetable broth", "2 tbsp butter or olive oil", "1 inch ginger", "1 knob butter",
  "2 scoops protein powder", "1 (15 oz) can", "1 (15 oz) can beans (2 cups)", "\u2153 cup flour (", "1 (", "1 ...", "2 8 oz steaks",
  "1 15-oz can, crushed tomatoes", "1/30000 cup salt", "%j \u2192 no suggestion",
  "1 can \u00d7 15 oz; kept the first amount; dropped (2 cups)", "parsed lines never carry a suggestion",
  "a name needs at least one letter", "no ingredient name", "2 cups ...", "2 cups cr\u00e8me fra\u00eeche", "cr\u00e8me fra\u00eeche",
  "%j", "property-style sweep", "10", "0.25", ".5", "1/2", "3/4", "1/3", "2/3", "\u2153", "1 1/3", "1\u2153", "1\u00bd", "2-3", "1 to 2",
  "1 or 2", "\u2153-\u00bd", "0", "1/0", "12345", "1,5", "cups", "Tbsp", "T", "lbs", "L", "fl oz", "quart", "pints", "gal", "can", "cans",
  "cloves", "bunch", "pinch", "dash", "slices", "stick", "knob", "(15 oz) can", "can (14.5 oz)", "(6-ounce)", "15-oz can", "(240 ml)",
  "of", "garlic", "milk or cream", "chicken or vegetable broth", "cheddar (shredded)", "rice (1 cup)", "2% milk", ", to taste", " ($0.16)",
  " (optional)", ", plus 2 tbsp", " to taste", ", or 1 cup water", " ($1.23*)", ", divided", "- ", "\u2022 ", "optional: ", "a ",
  "every line keeps the contract and every proposal satisfies the invariants", " ",
  "a proposal's quantity is an exact decimal or carries a rounding note", "\u2153 cup a", "1/7 cup b", "2/9 tsp c", "5/6 quart d",
  "1/3 (15 oz) can e", "1/3 (2/3 oz) packet f", "3/11 cup g", ".", "0.2222", "3.3333", "5/9 cup x", "0.5556", "hostile input",
  "never throws, stays bounded and keeps the invariants", "(15 oz) ", "(14.5 oz) ", "1 or ", "2-", "milk or ", "a, ", "($0.16) ", "9",
  "large ", "can ", "<script>alert(1)</script> 1 cup", "\u0000\u202e1 cup milk", "(a(b(c",
];
