#!/usr/bin/env python3
"""Build regressions/r1-round3-findings.tsv from candidate review R1 round 3 (at ea674ec): every firm line in the
reported sections of RESULTS-new.md and RESULTS-prior.md (HIGH, regressions, review burden, other C3, C5b, other C8),
with R1's labels from its probe files. R1's other new probes are not included.
Usage: python3 -I make_r1r3_findings.py <review4-dir> <out.tsv>
"""
import re, sys, os
d, out = sys.argv[1], sys.argv[2]
tsv = {}
for f in ("probes-r3-new.tsv", "probes-prior-round3.tsv"):
    for line in open(os.path.join(d, f)):
        if line.startswith("#") or not line.strip(): continue
        c = line.rstrip("\n").split("\t"); tsv.setdefault(c[0], c)
KEEP = ("HIGH lines, firm", "Regressions", "C3 not caused", "C3 recognised-food abstentions", "C5b", "Other C8")
rows, missing, seen = [], [], set()
for res, tag in (("RESULTS-new.md", "R1R3-NEW"), ("RESULTS-prior.md", "R1R3-PRIOR")):
    text = open(os.path.join(d, res)).read()
    for sec in re.split(r"\n## ", text):
        title = sec.split("\n")[0]
        if not title.startswith(KEEP): continue
        for m in re.finditer(r"^- \[([^\]]*)\] `([^`]*)`", sec, re.M):
            inp = m.group(2).replace("\\|", "|")
            if inp in seen: continue
            seen.add(inp)
            if inp not in tsv: missing.append(inp); continue
            c = tsv[inp]
            if "D" in c[7]: continue
            cols = c[:7]
            if "S" in c[7]: cols[2:7] = ["*"] * 5
            g = m.group(1)
            fam = "D" if g.startswith("E") else "A" if g.startswith(("U", "M")) else "-"
            rows.append(cols + ["-", f"{tag}:{title.split(' (')[0]}", fam])
with open(out, "w") as fh:
    fh.write("# R1 round-3 reported lines (generated by make_r1r3_findings.py); columns as coordinator-labels.tsv.\n")
    for r in rows: fh.write("\t".join(r) + "\n")
print(len(rows), "rows;", len(missing), "missing:", missing[:10])
