#!/usr/bin/env python3
"""Build regressions/r1-findings.tsv: the counterexamples the candidate review (R1, round 1) reported — every firm HIGH
line (HIGH-LINES.md) and the MEDIUM reproductions of CANDIDATE-REVIEW.md — with R1's labels, adjusted only where a
CONTRACT §12.A amendment decides differently (A3: prepared same food restated as whole items → ready).
R1's other probes are NOT included (they stay unseen by the implementation worker for the re-review).
Usage: python3 -I make_r1_findings.py <r1-review-dir> <out.tsv>
"""
import re, sys, os
d, out = sys.argv[1], sys.argv[2]
tsv = {}
for f in ("probes-r1.tsv", "probes-r1-supplement.tsv"):
    for line in open(os.path.join(d, f)):
        if line.startswith("#") or not line.strip(): continue
        c = line.rstrip("\n").split("\t"); tsv[c[0]] = c
hl = open(os.path.join(d, "HIGH-LINES.md")).read().split("## Debatable")[0]
high = [re.search(r"`([^`]*)`", r).group(1).replace("\\|", "|") for r in hl.split("\n") if r.startswith("| main") or r.startswith("| supp")]
medium = ["1 cup almond or cashew butter", "1 lb pork or chicken sausage", "1 lb chicken or turkey sausage", "1 pint cherry or grape tomatoes",
          "1 cup peanut or almond butter", "1 tsp onion or garlic salt", "1 lb beef or pork tenderloin", "1 cup coconut or brown sugar",
          "1 cup macadamia or cashew nuts", "4 slider or dinner rolls", "1 tbsp yellow or Dijon mustard", "2 cups apple or pear cider",
          "4 oz dark or milk chocolate", "1 cup white or whole wheat flour", "1 cup red, yellow, or orange bell pepper, diced",
          "1 cup red, green, or yellow bell pepper", "2 cups red, yellow or orange peppers", "1 cup flour (all-purpose or whole wheat)",
          "2 apples, Granny Smith or Honeycrisp", "1 lb Yukon Gold potatoes or red", "1 #10 can diced tomatoes", "2 No. 303 cans cut green beans",
          "1 (No. 2) can corn", "2 cups minus 1/4 cup sugar", "2 three cheese pizzas", "1 tbsp Heinz 57 sauce", "a half-inch piece fresh ginger"]
A3_PREPARED = {"(2 medium carrots)", "(about 2 cups chopped)", "(1 medium onion)", "(about 3 tomatoes)", "(2 ripe bananas)", "(about 1 medium)"}
rows, missing = [], []
for kind, items in (("R1-HIGH", high), ("R1-MEDIUM", medium)):
    for inp in items:
        if inp not in tsv: missing.append(inp); continue
        c = tsv[inp][:]
        flags = c[7]
        if "D" in flags: continue
        status_only = "S" in flags
        if any(p in inp for p in A3_PREPARED) and c[1] == "needs_review":
            c[1] = "ready"; status_only = False  # CONTRACT §12.A A3
            kind2 = kind + "+A3"
        else:
            kind2 = kind
        if status_only:  # R1 labelled only the status: other fields unchecked
            c[2:7] = ["*", "*", "*", "*", "*"]
        fam = c[8].split("-")[0] if c[8][:1] in "ABCD" else "-"
        rows.append([c[0], c[1], c[2], c[3], c[4], c[5], c[6], "-", kind2, fam if fam in ("A", "B", "C", "D") else "-"])
with open(out, "w") as fh:
    fh.write("# R1 candidate-review counterexamples (generated by make_r1_findings.py). Columns as coordinator-labels.tsv; origin = R1-HIGH / R1-MEDIUM (+A3 = relabelled by CONTRACT §12.A A3).\n")
    for r in rows: fh.write("\t".join(r) + "\n")
print(len(rows), "rows;", len(missing), "missing:", missing)
