#!/usr/bin/env python3
"""Build regressions/r1-round2-findings.tsv: the counterexamples candidate review R1 round 2 (at a8b76db) reported —
every firm HIGH line (HIGH-LINES-2.md), the regressions and the review-only issues listed in CANDIDATE-REVIEW-2.md —
with R1's labels (fresh probes, or round-1 probes as relabelled in RELABELLED.md). R1's other fresh probes are NOT
included. Usage: python3 -I make_r1r2_findings.py <review3-dir> <out.tsv>
"""
import re, sys, os
d, out = sys.argv[1], sys.argv[2]
tsv = {}
for f in ("probes-fresh.tsv", "probes-r1-round2.tsv"):
    for line in open(os.path.join(d, f)):
        if line.startswith("#") or not line.strip(): continue
        c = line.rstrip("\n").split("\t"); tsv.setdefault(c[0], c)
hl = open(os.path.join(d, "HIGH-LINES-2.md")).read()
firm_part = re.split(r"\n## .*[Dd]ebatable", hl)[0]
high = [re.search(r"`([^`]*)`", r).group(1).replace("\\|", "|") for r in firm_part.split("\n") if r.startswith("| ") and "`" in r and not r.startswith("| group")]
reported = ["6 finger sandwiches", "3 stone crab claws", "2 slab pies", "1 chicken pot pie", "2 rolls, split", "1 leg of lamb (about 5 lb)",
            "1 rack of lamb, frenched", "2 racks of lamb", "4 bread bowls", "4 tortilla bowls", "12 wonton cups", "6 lettuce cups", "8 phyllo cups",
            "2 tbsp lemon and lime juice", "1 jar black bean and corn salsa", "1 pack bacon and cheese pierogies", "1 bag apple and cinnamon oatmeal",
            "1 jar garlic and herb cream cheese", "1 lb large shrimp (21-25 count)", "2 cups vanilla or plain yogurt",
            "1 tbsp date or maple syrup", "1 cup chocolate or butterscotch chips", "2 cups acorn or butternut squash", "1 tbsp clover or wildflower honey",
            "2 chamomile or mint tea bags", "1 lb Black Forest or honey ham", "8 slices turkey or pork bacon", "1/2 cup rice or plum wine",
            "1 cup goat or sheep milk yogurt", "2 cups pear or apple sauce", "2 tbsp mango or peach chutney", "1 lb spinach or egg fettuccine",
            "2 cups vanilla or chocolate pudding", "1 tsp lavender or rose water", "1 lb Mexican or Spanish chorizo",
            "1 #2½ can pumpkin purée", "2 No. 2 1/2 cans apricots", "1 large (#2) can crushed pineapple", "Scant cup sugar"]
rows, missing = [], []
for kind, items in (("R1R2-HIGH", high), ("R1R2-REPORTED", reported)):
    for inp in items:
        if inp not in tsv: missing.append(inp); continue
        c = tsv[inp]
        if "D" in c[7]: continue
        cols = c[:7]
        if "S" in c[7]: cols[2:7] = ["*", "*", "*", "*", "*"]
        g = c[8] if len(c) > 8 else ""
        FAM = {"F-equip": "D", "F-furniture": "D", "F-nutrition": "D", "F-equipfood": "D", "F-nutrfood": "D",
               "F-unknown": "A", "F-measurefood": "A", "F-restate": "A", "F-quantity": "A", "F-nonumber": "A", "F-can": "A", "F-remark": "A",
               "F-and": "B", "F-choice": "B", "F-countword": "C"}
        fam = FAM.get(g, "-")
        rows.append(cols + ["-", kind, fam])
with open(out, "w") as fh:
    fh.write("# R1 round-2 counterexamples (generated by make_r1r2_findings.py); columns as coordinator-labels.tsv.\n")
    for r in rows: fh.write("\t".join(r) + "\n")
print(len(high), "high;", len(rows), "rows;", len(missing), "missing:", missing)
