/**
 * Generates the read-only unit-alias manifest (CONTRACT-v1 §13.1) from `src/unit-aliases.ts` and
 * `src/contract.ts` `UNIT_REGISTRY`. The manifest is never edited by hand; `tests/contract/unit-aliases.test.ts`
 * fails when the checked-in file differs from this output.
 *
 * Usage (from packages/recipe-extraction): npx tsx tools/unit-manifest/generate.ts [--write]
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { UNIT_REGISTRY, type UnitCode } from "../../src/contract";
import { CASED_UNIT_ALIASES, FLUID_OUNCE_WORDS, NOT_ALIASES, UNIT_ALIASES } from "../../src/unit-aliases";

export const MANIFEST_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../../docs/table/recipe-extraction/UNIT-ALIASES-v1.md");

export function renderManifest(): string {
  const out: string[] = [
    "# Unit aliases — contract v1 (generated, read-only)",
    "",
    "_Generated by `packages/recipe-extraction/tools/unit-manifest/generate.ts` from `src/unit-aliases.ts` and `UNIT_REGISTRY`",
    "(`src/contract.ts`). Do not edit: `tests/contract/unit-aliases.test.ts` fails when this file differs from the generated",
    "text. Rule: CONTRACT-v1 §13.1. Engines created before Phase 2C (`semantic-v1`, `semantic-v2`, the legacy copies) keep their",
    "own frozen word lists; this table is what the contract declares._",
    "",
    "| Code | Dimension | Base | Declared written words (lower case; a final period is ignored) |",
    "|---|---|---|---|",
  ];
  for (const code of Object.keys(UNIT_REGISTRY) as UnitCode[]) {
    const def = UNIT_REGISTRY[code];
    out.push(`| \`${code}\` | ${def.dimension} | ${def.base ?? "—"} | ${UNIT_ALIASES[code].map((w) => `\`${w}\``).join(", ")} |`);
  }
  out.push("", "**Case-sensitive spellings:** " + Object.entries(CASED_UNIT_ALIASES).map(([w, c]) => `\`${w}\` → \`${c}\``).join(", ") + ".");
  out.push("", `**Fluid ounce (two words):** ${FLUID_OUNCE_WORDS.map((w) => `\`${w}\``).join(" or ")} followed by an \`oz\` word → \`fl_oz\`.`);
  out.push("", "**Not aliases** (a different noun; an amount before it is CONTRACT §12.14 → `needs_review`):", "");
  out.push("| Word | Why |", "|---|---|");
  for (const [w, why] of Object.entries(NOT_ALIASES)) out.push(`| \`${w}\` | ${why} |`);
  out.push("");
  return out.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const text = renderManifest();
  if (process.argv.includes("--write")) writeFileSync(MANIFEST_PATH, text);
  else process.stdout.write(text);
  if (!process.argv.includes("--write")) {
    let cur = "";
    try { cur = readFileSync(MANIFEST_PATH, "utf8"); } catch { /* absent */ }
    if (cur !== text) process.stderr.write("manifest differs from the checked-in file (run with --write)\n");
  }
}
